server:
  port: 8090

#数据库连接配置
spring:
  datasource:
#    mysql: # mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.91.125.8:3307/daas3
    username: root
    password: Gci@123456
  doris: # doris配置
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://10.91.125.43:9030/daas_sjz
  username: root
  password: s#ab4s2e

logging:
  level:
    root: INFO
    com.example: DEBUG